# Generated by Django 5.2.8 on 2025-11-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artiste', models.CharField(max_length=100)),
                ('titre', models.CharField(max_length=100)),
                ('duree', models.PositiveIntegerField(help_text='Durée en secondes')),
                ('style', models.CharField(max_length=50)),
            ],
        ),
    ]
