# Generated by Django 5.2.8 on 2025-11-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('duration', models.CharField(blank=True, max_length=10, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
